services:
  TemplateNameProject:
    image: mcr.microsoft.com/mssql/server:latest
  
  # distributedcache:
  #   image: redis
  
  # seq:
  #   image: datalust/seq:latest
  
  # messagebus:
  #   image: rabbitmq:3-management
  
  # identity:
  #   image: quay.io/keycloak/keycloak                                                                                                                             
  
  
volumes:
  sqlserver_TemplateNameProject:

