services:
  TemplateNameProject:
    container_name: TemplateNameProject
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=MyReallyStrongPassword123!
    restart: always
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_TemplateNameProject:/var/opt/mssql
  
  # distributedcache:
  #   container_name: distributedcache
  #   restart: always
  #   ports:
  #     - "6379:6379"
  
  # seq:
  #   container_name: seq
  #   environment:
  #     - ACCEPT_EULA=Y
  #     # - SEQ_FIRSTRUN_ADMINPASSWORD=MyReallyStrongPassword
  #     - SEQ_FIRSTRUN_NOAUTHENTICATION=true
  #   restart: always
  #   ports:
  #     - "5341:5341"
  #     - "9091:80"
  
  # messagebus:
  #   container_name: messagebus
  #   hostname: ecommerce-mq
  #   environment:
  #     - RABBITMQ_DEFAULT_USER=guest
  #     - RABBITMQ_DEFAULT_PASS=guest
  #   restart: always
  #   ports:
  #     - "5672:5672"
  #     - "15672:15672"
  
  # identity:
  #   container_name: identity
  #   environment:
  #     - KEYCLOAK_ADMIN=admin
  #     - KEYCLOAK_ADMIN_PASSWORD=admin
  #     - KC_DB=postgres
  #     - KC_DB_URL=jdbc:postgresql://TemplateNameProject/TemplateNameProject?currentSchema=identity
  #     - KC_DB_USERNAME=postgres
  #     - KC_DB_PASSWORD=postgres
  #   restart: always
  #   ports:
  #     - "9090:8080"
  #   command:
  #     - start-dev
